lint:
  files_unchanged:
    - assets/nf-core-nanoporemetabarcoding_logo_light.png
    - docs/images/nf-core-nanoporemetabarcoding_logo_light.png
    - docs/images/nf-core-nanoporemetabarcoding_logo_dark.png
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Fernando Duarte,  Chris Wyatt
  description: Metabarcoding analysis using nanopore sequecing
  force: false
  is_nfcore: true
  name: nanoporemetabarcoding
  org: nf-core
  outdir: .
  version: 1.0.0dev
